services:
  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_DB: deezcode
      POSTGRES_USER: spectrefury
      POSTGRES_PASSWORD: Ayushsoni2212

    ports: 
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


